// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Recording {
    pub id: String,
    pub file_path: String,
    pub duration_secs: f64,
    pub sample_count: u64,
    pub stop_reason: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub active_window_app_name: Option<String>,
    pub active_window_bundle_id: Option<String>,
    pub active_window_title: Option<String>,
}

impl __sdk::InModule for Recording {
    type Module = super::RemoteModule;
}
